language: node_js
node_js:
    - "4.1"
    - "4.0"
    - "0.12"
    - "0.11"
    - "0.10"

install:
    - npm install

script:
    - npm test

notifications:
    email:
        recipients:
            - cslabas@gmail.com
        on_success: always
