resources:
- name: source
  type: git
  source:
    uri: https://github.com/chazzlabs/angular_example
    branch: master

jobs:
- name: unit-test
  plan:
  - get: source
    trigger: true
  - task: unit
    file: angular_example/ci/test.yml
